# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('createdDate', models.DateTimeField()),
                ('publishedDate', models.DateTimeField()),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
    ]
